-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE `pokemons` (
	`national_number` integer,
	`gen` text,
	`english_name` text,
	`japanese_name` text,
	`primary_type` text,
	`secondary_type` text,
	`classification` text,
	`percent_male` text,
	`percent_female` text,
	`height_m` real,
	`weight_kg` real,
	`capture_rate` text,
	`base_egg_steps` integer,
	`hp` integer,
	`attack` integer,
	`defense` integer,
	`sp_attack` integer,
	`sp_defense` integer,
	`speed` integer,
	`abilities_0` text,
	`abilities_1` text,
	`abilities_2` text,
	`abilities_hidden` text,
	`against_normal` real,
	`against_fire` real,
	`against_water` real,
	`against_electric` real,
	`against_grass` real,
	`against_ice` real,
	`against_fighting` real,
	`against_poison` real,
	`against_ground` real,
	`against_flying` real,
	`against_psychic` real,
	`against_bug` real,
	`against_rock` real,
	`against_ghost` real,
	`against_dragon` real,
	`against_dark` real,
	`against_steel` real,
	`against_fairy` real,
	`is_sublegendary` integer,
	`is_legendary` integer,
	`is_mythical` integer,
	`evochain_0` text,
	`evochain_1` text,
	`evochain_2` text,
	`evochain_3` text,
	`evochain_4` text,
	`evochain_5` text,
	`evochain_6` text,
	`gigantamax` text,
	`mega_evolution` text,
	`mega_evolution_alt` text,
	`description` text
);

*/