/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../src/pages/__root'
import { Route as IndexImport } from './../src/pages/index'
import { Route as pokemonsPokemonsImport } from './../src/pages/(pokemons)/pokemons'
import { Route as pokemonsPokemonsIndexImport } from './../src/pages/(pokemons)/pokemons.index'
import { Route as pokemonsPokemonsPokemonNameImport } from './../src/pages/(pokemons)/pokemons_.$pokemonName'
import { Route as pokemonsPokemonsTypesImport } from './../src/pages/(pokemons)/pokemons.types'
import { Route as pokemonsPokemonsAboutImport } from './../src/pages/(pokemons)/pokemons.about'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const pokemonsPokemonsRoute = pokemonsPokemonsImport.update({
  id: '/(pokemons)/pokemons',
  path: '/pokemons',
  getParentRoute: () => rootRoute,
} as any)

const pokemonsPokemonsIndexRoute = pokemonsPokemonsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => pokemonsPokemonsRoute,
} as any)

const pokemonsPokemonsPokemonNameRoute =
  pokemonsPokemonsPokemonNameImport.update({
    id: '/(pokemons)/pokemons_/$pokemonName',
    path: '/pokemons/$pokemonName',
    getParentRoute: () => rootRoute,
  } as any)

const pokemonsPokemonsTypesRoute = pokemonsPokemonsTypesImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => pokemonsPokemonsRoute,
} as any)

const pokemonsPokemonsAboutRoute = pokemonsPokemonsAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => pokemonsPokemonsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(pokemons)/pokemons': {
      id: '/(pokemons)/pokemons'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof pokemonsPokemonsImport
      parentRoute: typeof rootRoute
    }
    '/(pokemons)/pokemons/about': {
      id: '/(pokemons)/pokemons/about'
      path: '/about'
      fullPath: '/pokemons/about'
      preLoaderRoute: typeof pokemonsPokemonsAboutImport
      parentRoute: typeof pokemonsPokemonsImport
    }
    '/(pokemons)/pokemons/types': {
      id: '/(pokemons)/pokemons/types'
      path: '/types'
      fullPath: '/pokemons/types'
      preLoaderRoute: typeof pokemonsPokemonsTypesImport
      parentRoute: typeof pokemonsPokemonsImport
    }
    '/(pokemons)/pokemons_/$pokemonName': {
      id: '/(pokemons)/pokemons_/$pokemonName'
      path: '/pokemons/$pokemonName'
      fullPath: '/pokemons/$pokemonName'
      preLoaderRoute: typeof pokemonsPokemonsPokemonNameImport
      parentRoute: typeof rootRoute
    }
    '/(pokemons)/pokemons/': {
      id: '/(pokemons)/pokemons/'
      path: '/'
      fullPath: '/pokemons/'
      preLoaderRoute: typeof pokemonsPokemonsIndexImport
      parentRoute: typeof pokemonsPokemonsImport
    }
  }
}

// Create and export the route tree

interface pokemonsPokemonsRouteChildren {
  pokemonsPokemonsAboutRoute: typeof pokemonsPokemonsAboutRoute
  pokemonsPokemonsTypesRoute: typeof pokemonsPokemonsTypesRoute
  pokemonsPokemonsIndexRoute: typeof pokemonsPokemonsIndexRoute
}

const pokemonsPokemonsRouteChildren: pokemonsPokemonsRouteChildren = {
  pokemonsPokemonsAboutRoute: pokemonsPokemonsAboutRoute,
  pokemonsPokemonsTypesRoute: pokemonsPokemonsTypesRoute,
  pokemonsPokemonsIndexRoute: pokemonsPokemonsIndexRoute,
}

const pokemonsPokemonsRouteWithChildren =
  pokemonsPokemonsRoute._addFileChildren(pokemonsPokemonsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemons': typeof pokemonsPokemonsRouteWithChildren
  '/pokemons/about': typeof pokemonsPokemonsAboutRoute
  '/pokemons/types': typeof pokemonsPokemonsTypesRoute
  '/pokemons/$pokemonName': typeof pokemonsPokemonsPokemonNameRoute
  '/pokemons/': typeof pokemonsPokemonsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemons/about': typeof pokemonsPokemonsAboutRoute
  '/pokemons/types': typeof pokemonsPokemonsTypesRoute
  '/pokemons/$pokemonName': typeof pokemonsPokemonsPokemonNameRoute
  '/pokemons': typeof pokemonsPokemonsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(pokemons)/pokemons': typeof pokemonsPokemonsRouteWithChildren
  '/(pokemons)/pokemons/about': typeof pokemonsPokemonsAboutRoute
  '/(pokemons)/pokemons/types': typeof pokemonsPokemonsTypesRoute
  '/(pokemons)/pokemons_/$pokemonName': typeof pokemonsPokemonsPokemonNameRoute
  '/(pokemons)/pokemons/': typeof pokemonsPokemonsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pokemons'
    | '/pokemons/about'
    | '/pokemons/types'
    | '/pokemons/$pokemonName'
    | '/pokemons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pokemons/about'
    | '/pokemons/types'
    | '/pokemons/$pokemonName'
    | '/pokemons'
  id:
    | '__root__'
    | '/'
    | '/(pokemons)/pokemons'
    | '/(pokemons)/pokemons/about'
    | '/(pokemons)/pokemons/types'
    | '/(pokemons)/pokemons_/$pokemonName'
    | '/(pokemons)/pokemons/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  pokemonsPokemonsRoute: typeof pokemonsPokemonsRouteWithChildren
  pokemonsPokemonsPokemonNameRoute: typeof pokemonsPokemonsPokemonNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  pokemonsPokemonsRoute: pokemonsPokemonsRouteWithChildren,
  pokemonsPokemonsPokemonNameRoute: pokemonsPokemonsPokemonNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(pokemons)/pokemons",
        "/(pokemons)/pokemons_/$pokemonName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(pokemons)/pokemons": {
      "filePath": "(pokemons)/pokemons.tsx",
      "children": [
        "/(pokemons)/pokemons/about",
        "/(pokemons)/pokemons/types",
        "/(pokemons)/pokemons/"
      ]
    },
    "/(pokemons)/pokemons/about": {
      "filePath": "(pokemons)/pokemons.about.tsx",
      "parent": "/(pokemons)/pokemons"
    },
    "/(pokemons)/pokemons/types": {
      "filePath": "(pokemons)/pokemons.types.tsx",
      "parent": "/(pokemons)/pokemons"
    },
    "/(pokemons)/pokemons_/$pokemonName": {
      "filePath": "(pokemons)/pokemons_.$pokemonName.tsx"
    },
    "/(pokemons)/pokemons/": {
      "filePath": "(pokemons)/pokemons.index.tsx",
      "parent": "/(pokemons)/pokemons"
    }
  }
}
ROUTE_MANIFEST_END */
