/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as pokemonsPokemonsImport } from './routes/(pokemons)/pokemons'
import { Route as pokemonsPokemonsPokemonImport } from './routes/(pokemons)/pokemons_.$pokemon'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const pokemonsPokemonsRoute = pokemonsPokemonsImport.update({
  id: '/(pokemons)/pokemons',
  path: '/pokemons',
  getParentRoute: () => rootRoute,
} as any)

const pokemonsPokemonsPokemonRoute = pokemonsPokemonsPokemonImport.update({
  id: '/(pokemons)/pokemons_/$pokemon',
  path: '/pokemons/$pokemon',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(pokemons)/pokemons': {
      id: '/(pokemons)/pokemons'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof pokemonsPokemonsImport
      parentRoute: typeof rootRoute
    }
    '/(pokemons)/pokemons_/$pokemon': {
      id: '/(pokemons)/pokemons_/$pokemon'
      path: '/pokemons/$pokemon'
      fullPath: '/pokemons/$pokemon'
      preLoaderRoute: typeof pokemonsPokemonsPokemonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemons': typeof pokemonsPokemonsRoute
  '/pokemons/$pokemon': typeof pokemonsPokemonsPokemonRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemons': typeof pokemonsPokemonsRoute
  '/pokemons/$pokemon': typeof pokemonsPokemonsPokemonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(pokemons)/pokemons': typeof pokemonsPokemonsRoute
  '/(pokemons)/pokemons_/$pokemon': typeof pokemonsPokemonsPokemonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemons' | '/pokemons/$pokemon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemons' | '/pokemons/$pokemon'
  id:
    | '__root__'
    | '/'
    | '/(pokemons)/pokemons'
    | '/(pokemons)/pokemons_/$pokemon'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  pokemonsPokemonsRoute: typeof pokemonsPokemonsRoute
  pokemonsPokemonsPokemonRoute: typeof pokemonsPokemonsPokemonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  pokemonsPokemonsRoute: pokemonsPokemonsRoute,
  pokemonsPokemonsPokemonRoute: pokemonsPokemonsPokemonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(pokemons)/pokemons",
        "/(pokemons)/pokemons_/$pokemon"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(pokemons)/pokemons": {
      "filePath": "(pokemons)/pokemons.tsx"
    },
    "/(pokemons)/pokemons_/$pokemon": {
      "filePath": "(pokemons)/pokemons_.$pokemon.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
