/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FileImport } from './routes/file'
import { Route as AboutImport } from './routes/about'
import { Route as PostsRouteImport } from './routes/posts/route'
import { Route as PokemonsRouteImport } from './routes/pokemons/route'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts/index'
import { Route as PokemonsIndexImport } from './routes/pokemons/index'
import { Route as PostsPostIdImport } from './routes/posts/$postId'
import { Route as PostsPostIdEditImport } from './routes/posts/$postId.edit'

// Create/Update Routes

const FileRoute = FileImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const PostsRouteRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const PokemonsRouteRoute = PokemonsRouteImport.update({
  id: '/pokemons',
  path: '/pokemons',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)

const PokemonsIndexRoute = PokemonsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PokemonsRouteRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)

const PostsPostIdEditRoute = PostsPostIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostsPostIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemons': {
      id: '/pokemons'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof PokemonsRouteImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/file': {
      id: '/file'
      path: '/file'
      fullPath: '/file'
      preLoaderRoute: typeof FileImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof PostsRouteImport
    }
    '/pokemons/': {
      id: '/pokemons/'
      path: '/'
      fullPath: '/pokemons/'
      preLoaderRoute: typeof PokemonsIndexImport
      parentRoute: typeof PokemonsRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof PostsRouteImport
    }
    '/posts/$postId/edit': {
      id: '/posts/$postId/edit'
      path: '/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof PostsPostIdEditImport
      parentRoute: typeof PostsPostIdImport
    }
  }
}

// Create and export the route tree

interface PokemonsRouteRouteChildren {
  PokemonsIndexRoute: typeof PokemonsIndexRoute
}

const PokemonsRouteRouteChildren: PokemonsRouteRouteChildren = {
  PokemonsIndexRoute: PokemonsIndexRoute,
}

const PokemonsRouteRouteWithChildren = PokemonsRouteRoute._addFileChildren(
  PokemonsRouteRouteChildren,
)

interface PostsPostIdRouteChildren {
  PostsPostIdEditRoute: typeof PostsPostIdEditRoute
}

const PostsPostIdRouteChildren: PostsPostIdRouteChildren = {
  PostsPostIdEditRoute: PostsPostIdEditRoute,
}

const PostsPostIdRouteWithChildren = PostsPostIdRoute._addFileChildren(
  PostsPostIdRouteChildren,
)

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRouteWithChildren
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRouteWithChildren,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemons': typeof PokemonsRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/file': typeof FileRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/pokemons/': typeof PokemonsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/file': typeof FileRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/pokemons': typeof PokemonsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pokemons': typeof PokemonsRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/file': typeof FileRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/pokemons/': typeof PokemonsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pokemons'
    | '/posts'
    | '/about'
    | '/file'
    | '/posts/$postId'
    | '/pokemons/'
    | '/posts/'
    | '/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/file'
    | '/posts/$postId'
    | '/pokemons'
    | '/posts'
    | '/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/pokemons'
    | '/posts'
    | '/about'
    | '/file'
    | '/posts/$postId'
    | '/pokemons/'
    | '/posts/'
    | '/posts/$postId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonsRouteRoute: typeof PokemonsRouteRouteWithChildren
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  FileRoute: typeof FileRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonsRouteRoute: PokemonsRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  FileRoute: FileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pokemons",
        "/posts",
        "/about",
        "/file"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pokemons": {
      "filePath": "pokemons/route.tsx",
      "children": [
        "/pokemons/"
      ]
    },
    "/posts": {
      "filePath": "posts/route.tsx",
      "children": [
        "/posts/$postId",
        "/posts/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/file": {
      "filePath": "file.tsx"
    },
    "/posts/$postId": {
      "filePath": "posts/$postId.tsx",
      "parent": "/posts",
      "children": [
        "/posts/$postId/edit"
      ]
    },
    "/pokemons/": {
      "filePath": "pokemons/index.tsx",
      "parent": "/pokemons"
    },
    "/posts/": {
      "filePath": "posts/index.tsx",
      "parent": "/posts"
    },
    "/posts/$postId/edit": {
      "filePath": "posts/$postId.edit.tsx",
      "parent": "/posts/$postId"
    }
  }
}
ROUTE_MANIFEST_END */
