/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as pokemonsPokemonsRouteImport } from './routes/(pokemons)/pokemons'
import { Route as pokemonsPokemonsIndexRouteImport } from './routes/(pokemons)/pokemons.index'
import { Route as pokemonsPokemonsPokemonNameRouteImport } from './routes/(pokemons)/pokemons_.$pokemonName'
import { Route as pokemonsPokemonsTypesRouteImport } from './routes/(pokemons)/pokemons.types'
import { Route as pokemonsPokemonsAboutRouteImport } from './routes/(pokemons)/pokemons.about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pokemonsPokemonsRoute = pokemonsPokemonsRouteImport.update({
  id: '/(pokemons)/pokemons',
  path: '/pokemons',
  getParentRoute: () => rootRouteImport,
} as any)
const pokemonsPokemonsIndexRoute = pokemonsPokemonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => pokemonsPokemonsRoute,
} as any)
const pokemonsPokemonsPokemonNameRoute =
  pokemonsPokemonsPokemonNameRouteImport.update({
    id: '/(pokemons)/pokemons_/$pokemonName',
    path: '/pokemons/$pokemonName',
    getParentRoute: () => rootRouteImport,
  } as any)
const pokemonsPokemonsTypesRoute = pokemonsPokemonsTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => pokemonsPokemonsRoute,
} as any)
const pokemonsPokemonsAboutRoute = pokemonsPokemonsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => pokemonsPokemonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemons': typeof pokemonsPokemonsRouteWithChildren
  '/pokemons/about': typeof pokemonsPokemonsAboutRoute
  '/pokemons/types': typeof pokemonsPokemonsTypesRoute
  '/pokemons/$pokemonName': typeof pokemonsPokemonsPokemonNameRoute
  '/pokemons/': typeof pokemonsPokemonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemons/about': typeof pokemonsPokemonsAboutRoute
  '/pokemons/types': typeof pokemonsPokemonsTypesRoute
  '/pokemons/$pokemonName': typeof pokemonsPokemonsPokemonNameRoute
  '/pokemons': typeof pokemonsPokemonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(pokemons)/pokemons': typeof pokemonsPokemonsRouteWithChildren
  '/(pokemons)/pokemons/about': typeof pokemonsPokemonsAboutRoute
  '/(pokemons)/pokemons/types': typeof pokemonsPokemonsTypesRoute
  '/(pokemons)/pokemons_/$pokemonName': typeof pokemonsPokemonsPokemonNameRoute
  '/(pokemons)/pokemons/': typeof pokemonsPokemonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pokemons'
    | '/pokemons/about'
    | '/pokemons/types'
    | '/pokemons/$pokemonName'
    | '/pokemons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pokemons/about'
    | '/pokemons/types'
    | '/pokemons/$pokemonName'
    | '/pokemons'
  id:
    | '__root__'
    | '/'
    | '/(pokemons)/pokemons'
    | '/(pokemons)/pokemons/about'
    | '/(pokemons)/pokemons/types'
    | '/(pokemons)/pokemons_/$pokemonName'
    | '/(pokemons)/pokemons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  pokemonsPokemonsRoute: typeof pokemonsPokemonsRouteWithChildren
  pokemonsPokemonsPokemonNameRoute: typeof pokemonsPokemonsPokemonNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pokemons)/pokemons': {
      id: '/(pokemons)/pokemons'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof pokemonsPokemonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pokemons)/pokemons/': {
      id: '/(pokemons)/pokemons/'
      path: '/'
      fullPath: '/pokemons/'
      preLoaderRoute: typeof pokemonsPokemonsIndexRouteImport
      parentRoute: typeof pokemonsPokemonsRoute
    }
    '/(pokemons)/pokemons_/$pokemonName': {
      id: '/(pokemons)/pokemons_/$pokemonName'
      path: '/pokemons/$pokemonName'
      fullPath: '/pokemons/$pokemonName'
      preLoaderRoute: typeof pokemonsPokemonsPokemonNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pokemons)/pokemons/types': {
      id: '/(pokemons)/pokemons/types'
      path: '/types'
      fullPath: '/pokemons/types'
      preLoaderRoute: typeof pokemonsPokemonsTypesRouteImport
      parentRoute: typeof pokemonsPokemonsRoute
    }
    '/(pokemons)/pokemons/about': {
      id: '/(pokemons)/pokemons/about'
      path: '/about'
      fullPath: '/pokemons/about'
      preLoaderRoute: typeof pokemonsPokemonsAboutRouteImport
      parentRoute: typeof pokemonsPokemonsRoute
    }
  }
}

interface pokemonsPokemonsRouteChildren {
  pokemonsPokemonsAboutRoute: typeof pokemonsPokemonsAboutRoute
  pokemonsPokemonsTypesRoute: typeof pokemonsPokemonsTypesRoute
  pokemonsPokemonsIndexRoute: typeof pokemonsPokemonsIndexRoute
}

const pokemonsPokemonsRouteChildren: pokemonsPokemonsRouteChildren = {
  pokemonsPokemonsAboutRoute: pokemonsPokemonsAboutRoute,
  pokemonsPokemonsTypesRoute: pokemonsPokemonsTypesRoute,
  pokemonsPokemonsIndexRoute: pokemonsPokemonsIndexRoute,
}

const pokemonsPokemonsRouteWithChildren =
  pokemonsPokemonsRoute._addFileChildren(pokemonsPokemonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  pokemonsPokemonsRoute: pokemonsPokemonsRouteWithChildren,
  pokemonsPokemonsPokemonNameRoute: pokemonsPokemonsPokemonNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
